#!/usr/bin/env python
# -*-Python-*-
# 
# Reset the state of the HTML tree completely, erasing it and then
# re-reading all of the review files.
#

import reviews

if __name__ == '__main__':
    reviews.load()
    reviews.delete_all_posts()
    reviews.update_all_posts()


