#!/usr/bin/env python
# -*-Python-*-
#
# Reset the state of the weblog, HTML tree completely, erasing it and then
# re-reading all of the review files.
#

import reviews

if __name__ == '__main__':
    reviews.reset_weblog()

