#!/usr/bin/env python
# -*-Python-*-

""" 

Script: Scans all regular files in a directory and updates the
corresponding pickle files.

"""

import sys, os, pickle
import reviews

# XXX This won't erase a .pkl file if the corresponding regular file
# disappears.  If you rename files, be sure to delete all the pickle files.

for filename in os.listdir('.'):
    if (filename.endswith('.pkl') or filename.endswith('~') or
	filename == 'Makefile'):
	continue
    if not os.path.isfile(filename):
        continue

    pkl_file = reviews.get_pickle_filename(filename)
    if (not os.path.exists(pkl_file) or 
	 os.path.getmtime(pkl_file) < os.path.getmtime(filename)):
        # Read existing pickle
        if os.path.exists(pkl_file):
            input = open(pkl_file, 'rb')
            entry = pickle.load(input)
            input.close()
        else:
            entry = reviews.BibEntry(filename)
        
        input = open(filename, 'r')
        try:
            entry.parse(input)
        except RuntimeError:
            print 'Skipping', filename
        else:
            print 'Updating', filename
            entry.save()
        
        input.close()

