#!/usr/bin/env python3
# -*-Python-*-
#
# Description: Prints a list of the best books for each year.
#

import sys
import reviews

def get_entry_html(entry):
    """Returns HTML code for a link to the given entry."""

    authors = entry.fields.get('A')
    def flip (a):
        L = a.split(',', 1)
        if len(L) == 2:
            a = L[1] + ' ' + L[0]
        return a
    s = '<cite>' + entry.get_url() + '</cite>'
    if authors is not None:
        authors = [flip(a) for a in authors]
        s += ", " + (', '.join(authors))

    return s + ": "


if __name__ == '__main__':
    reviews.load()

    cur_year = None
    for entry in reviews.sort_by_chron():
        if entry.review_date is None:
            print(('Entry for %s lacks a reading date' % entry.fields.get('T')),
                  file=sys.stderr)
            continue

        # Print header if we've changed year.
        if cur_year is None or not entry.review_date.startswith(cur_year):
            cur_year = entry.review_date[:4]
            print(cur_year)

        if entry.fields.get('*'):
            print(get_entry_html(entry))
