#!/usr/bin/env python3
# -*-Python-*-
#
# Description: Erases all pickle files in the current directory tree.

import os
import reviews

def main ():
    for dir, dirnames, filenames in os.walk('.'):
        for filename in filenames:
            if (filename.startswith('.') and filename.endswith('.pkl')):
                path = os.path.join(dir, filename)
                os.remove(path)


if __name__ == '__main__':
    main()
